
// Icon mappings for AI tools
const KNOWN_ICON_MAPPINGS = {
  'kaedim': { slug: 'threedotjs', color: '10B981' },
  'meshy': { slug: 'threedotjs', color: 'FF6B6B' },
  'spline': { slug: 'threejs', color: '6366F1' },
  'autify': { slug: 'testinglibrary', color: 'EC4899' },
  'bruno': { slug: 'bruno', color: '000000' },
  'functionize': { slug: 'jest', color: '6366F1' },
  'hoppscotch': { slug: 'hoppscotch', color: '10B981' },
  'jmeter': { slug: 'apachejmeter', color: 'D24939' },
  'postman': { slug: 'postman', color: 'FF6C37' },
  'qawolf': { slug: 'jest', color: '22C55E' },
  'soapui': { slug: 'soap', color: 'F4D03F' },
  'amplitude': { slug: 'amplitude', color: '00A4EF' },
  'googleanalytics': { slug: 'googleanalytics', color: 'E37400' },
  'mixpanel': { slug: 'mixpanel', color: '8B5CF6' },
  'askcodi': { slug: 'codecov', color: '00A4EF' },
  'chefbyconvex': { slug: 'chef', color: 'EF4444' },
  'coderabbit': { slug: 'githubactions', color: 'E11D48' },
  'devin': { slug: 'dev.to', color: 'F97316' },
  'githubcopilot': { slug: 'githubcopilot', color: '6366F1' },
  'googleduetai': { slug: 'google', color: '4285F4' },
  'googlestitch': { slug: 'google', color: '10B981' },
  'greptile': { slug: 'grep', color: 'F59E0B' },
  'jules': { slug: 'julia', color: '7C3AED' },
  'kiro': { slug: 'kibana', color: '06B6D4' },
  'manus': { slug: 'man', color: '3B82F6' },
  'memex': { slug: 'memcached', color: 'F59E0B' },
  'mindstudio': { slug: 'minds', color: '7C3AED' },
  'mocha': { slug: 'mocha', color: '92400E' },
  'pantoai': { slug: 'pantone', color: 'EF4444' },
  'pythagora': { slug: 'python', color: '8B5CF6' },
  'sourceryai': { slug: 'sourcetree', color: '3B82F6' },
  'workik': { slug: 'workplace', color: 'EC4899' },
  'activepieces': { slug: 'activecampaign', color: '635BFF' },
  'clockwise': { slug: 'clock', color: '3B82F6' },
  'fellow': { slug: 'fellowship', color: '7C3AED' },
  'make': { slug: 'make', color: '7B68EE' },
  'pabblyconnect': { slug: 'packagist', color: '00A4EF' },
  'powerautomate': { slug: 'microsoftpowerautomate', color: '0066FF' },
  'shortwave': { slug: 'shortwave', color: 'FF6B6B' },
  'n8n': { slug: 'n8n', color: 'FF6D5A' },
  'automationanywhere': { slug: 'robotframework', color: '10B981' },
  'axiom': { slug: 'axiom', color: 'EF4444' },
  'inflection': { slug: 'inflection', color: 'EC4899' },
  'lasso': { slug: 'lasso', color: '3B82F6' },
  'make.com': { slug: 'make', color: '6366F1' },
  'salesforceeinstein': { slug: 'salesforce', color: '8B5CF6' },
  'zapier': { slug: 'zapier', color: 'F97316' },
  'arc': { slug: 'arcbrowser', color: 'FC5C65' },
  'brave': { slug: 'brave', color: 'FB542B' },
  'diabrowser': { slug: 'dia', color: 'FF6B35' },
  'perplexitycomet': { slug: 'perplexity', color: '2088FF' },
  'sigmaaibrowser': { slug: 'sigma', color: '6366F1' },
  'freshdesk': { slug: 'freshdesk', color: 'FF6A00' },
  'hubspot': { slug: 'hubspot', color: 'FF7A59' },
  'intercom': { slug: 'intercom', color: '1F8DED' },
  'plain': { slug: 'plain', color: '1F8DED' },
  'salesforce': { slug: 'salesforce', color: '00A1E0' },
  'zendesk': { slug: 'zendesk', color: '03363D' },
  'zohocrm': { slug: 'zoho', color: 'E42527' },
  'characterai': { slug: 'characterai', color: 'EC4899' },
  'chatgpt': { slug: 'openai', color: '10A37F' },
  'copilot': { slug: 'microsoftcopilot', color: '6366F1' },
  'poe': { slug: 'poe', color: 'FF4500' },
  'replika': { slug: 'replika', color: '8B5CF6' },
  'youcom': { slug: 'you', color: 'FF6B35' },
  'adobefirefly': { slug: 'adobe', color: '6366F1' },
  'artafact': { slug: 'artifactregistry', color: 'F97316' },
  'canvaai': { slug: 'canva', color: 'F59E0B' },
  'dalle3': { slug: 'openai', color: '3B82F6' },
  'descript': { slug: 'descript', color: 'EC4899' },
  'illustrateai': { slug: 'illustrator', color: '14B8A6' },
  'lumaai': { slug: 'lumen', color: '3B82F6' },
  'midjourney': { slug: 'midjourney', color: 'EC4899' },
  'photoroom': { slug: 'photon', color: '22C55E' },
  'photon': { slug: 'photon', color: '8B5CF6' },
  'runway': { slug: 'runwayml', color: '8B5CF6' },
  'sora': { slug: 'openai', color: '06B6D4' },
  'stablediffusion': { slug: 'stabilityai', color: 'F97316' },
  'suno': { slug: 'sun', color: '10B981' },
  'udio': { slug: 'udacity', color: 'EF4444' },
  'alation': { slug: 'ala', color: 'F97316' },
  'anaplan': { slug: 'anaplan', color: '06B6D4' },
  'askai': { slug: 'ask', color: '8B5CF6' },
  'datarobot': { slug: 'datarobot', color: '3B82F6' },
  'looker': { slug: 'looker', color: '10B981' },
  'thoughtspot': { slug: 'thoughtspot', color: '6366F1' },
  'trifacta': { slug: 'trifacta', color: 'EF4444' },
  'voiceql': { slug: 'voice', color: 'EC4899' },
  'blazesql': { slug: 'blazemeter', color: 'EC4899' },
  'camelai': { slug: 'apachecamel', color: '10B981' },
  'consensus': { slug: 'consensus', color: '6366F1' },
  'juliusai': { slug: 'julia', color: 'F59E0B' },
  'scholarcy': { slug: 'scholar', color: 'F97316' },
  'semanticscholar': { slug: 'semanticweb', color: '7C3AED' },
  'firebase': { slug: 'firebase', color: 'FFCA28' },
  'neon': { slug: 'neon', color: '000000' },
  'railway': { slug: 'railway', color: '336791' },
  'supabase': { slug: 'supabase', color: '3ECF8E' },
  'turso': { slug: 'turso', color: '00E699' },
  'digitalocean': { slug: 'digitalocean', color: '0061FF' },
  'netlify': { slug: 'netlify', color: '00C7B7' },
  'render': { slug: 'render', color: '1B1F24' },
  'vercel': { slug: 'vercel', color: '000000' },
  'anima': { slug: 'anima', color: 'EF4444' },
  'beautifulai': { slug: 'beautifulsoup', color: 'FF6B6B' },
  'canva': { slug: 'canva', color: '00C4CC' },
  'codeparrot': { slug: 'codecov', color: '22C55E' },
  'codiaai': { slug: 'codio', color: 'F97316' },
  'emergent': { slug: 'emergency', color: '2563EB' },
  'figmamake': { slug: 'figma', color: 'A259FF' },
  'kromio': { slug: 'kroma', color: '7C3AED' },
  'leonardoai': { slug: 'leonardo', color: '22C55E' },
  'pitch': { slug: 'pitch', color: 'FF6B6B' },
  'rork': { slug: 'r', color: '06B6D4' },
  'tiledev': { slug: 'tile', color: '3B82F6' },
  'visme': { slug: 'visme', color: '6366F1' },
  'v0': { slug: 'v', color: '18181B' },
  'commitgen': { slug: 'commitlint', color: 'F59E0B' },
  'dataherald': { slug: 'datagrip', color: '8B5CF6' },
  'githubcopilotx': { slug: 'github', color: '6366F1' },
  'mabl': { slug: 'mabl', color: 'EF4444' },
  'repair': { slug: 'repair', color: '3B82F6' },
  'snykcode': { slug: 'snyk', color: 'F97316' },
  'sourcegraphcody': { slug: 'sourcegraph', color: '22C55E' },
  'stoplight': { slug: 'stoplight', color: '06B6D4' },
  'swimm': { slug: 'swim', color: 'EC4899' },
  'tabnine': { slug: 'tabnine', color: '10B981' },
  'chatpdf': { slug: 'chat', color: '3B82F6' },
  'humataai': { slug: 'humane', color: '10B981' },
  'knolli': { slug: 'knowledgebase', color: 'F59E0B' },
  'pdfai': { slug: 'pdf', color: '6366F1' },
  'updfai': { slug: 'up', color: 'EC4899' },
  'bigcommerce': { slug: 'bigcommerce', color: '000000' },
  'shopify': { slug: 'shopify', color: '96BF48' },
  'wixecommerce': { slug: 'wix', color: 'F7A600' },
  'antigravity': { slug: 'antigravity', color: '6366F1' },
  'atoms': { slug: 'atom', color: 'F97316' },
  'base44': { slug: 'base', color: '14B8A6' },
  'codegeex': { slug: 'codegeex', color: '10B981' },
  'continuedev': { slug: 'confluence', color: 'F59E0B' },
  'cursor': { slug: 'cursor', color: '7C3AED' },
  'fleet': { slug: 'fleet', color: '7C3AED' },
  'jetbrainsai': { slug: 'jetbrains', color: 'F97316' },
  'kilocode': { slug: 'kibana', color: 'EC4899' },
  'playcode': { slug: 'play', color: 'E11D48' },
  'qoder': { slug: 'qodana', color: '8B5CF6' },
  'trae': { slug: 'travis', color: '3B82F6' },
  'void': { slug: 'void', color: '18181B' },
  'windsurf': { slug: 'wind', color: '06B6D4' },
  'zed': { slug: 'zedindustries', color: '22C55E' },
  'bench': { slug: 'bench', color: 'F06B6B' },
  'wealthfront': { slug: 'wealthfront', color: '00D09C' },
  'jotform': { slug: 'jotform', color: 'FFA500' },
  'tally': { slug: 'tally', color: 'EF4444' },
  'typeform': { slug: 'typeform', color: '262627' },
  'greenhouse': { slug: 'greenhouse', color: 'FF6B6B' },
  'lever': { slug: 'lever', color: '4285F4' },
  'myfitnesspal': { slug: 'myfitnesspal', color: '22C55E' },
  'wysa': { slug: 'wysa', color: 'FF6B6B' },
  'ideogram': { slug: 'ide', color: '8B5CF6' },
  'imagen': { slug: 'google', color: '6366F1' },
  'nightcafe': { slug: 'night', color: 'F59E0B' },
  'artificialsolutions': { slug: 'artificialintelligence', color: '22C55E' },
  'ayasdi': { slug: 'ayasdi', color: 'EF4444' },
  'casetext': { slug: 'case', color: '10B981' },
  'deepmindalphafold': { slug: 'deepmind', color: '3B82F6' },
  'fourkite': { slug: 'four', color: '06B6D4' },
  'ironclad': { slug: 'iron', color: 'EC4899' },
  'paradox': { slug: 'paradox', color: 'F59E0B' },
  'pathai': { slug: 'path', color: '6366F1' },
  'zesty': { slug: 'zesty', color: '8B5CF6' },
  'zillowai': { slug: 'zillow', color: 'F97316' },
  'amazonq': { slug: 'aws', color: '3B82F6' },
  'claude': { slug: 'anthropic', color: 'FF6D00' },
  'claudehaiku': { slug: 'anthropic', color: '14B8A6' },
  'deepseek': { slug: 'deepseek', color: '06B6D4' },
  'gpt4': { slug: 'openai', color: '10B981' },
  'gpt4o': { slug: 'openai', color: 'A78BFA' },
  'gemini': { slug: 'google', color: '4285F4' },
  'grok': { slug: 'xai', color: 'EC4899' },
  'jurassic': { slug: 'jurassic', color: '8B5CF6' },
  'llama': { slug: 'meta', color: '6366F1' },
  'microsoftcopilot': { slug: 'microsoft', color: '22C55E' },
  'mistral': { slug: 'mistralai', color: 'F97316' },
  'perplexity': { slug: 'perplexity', color: 'EF4444' },
  'qwen': { slug: 'alibabacloud', color: 'F59E0B' },
  'stablelm': { slug: 'stabilityai', color: '84CC16' },
  'coursera': { slug: 'coursera', color: '0056D2' },
  'duolingo': { slug: 'duolingo', color: '58CC02' },
  'khanacademy': { slug: 'khanacademy', color: '00C7B7' },
  'udemy': { slug: 'udemy', color: 'A435F0' },
  'lexion': { slug: 'lexicon', color: '003366' },
  'adcreativeai': { slug: 'adcreative', color: 'EC4899' },
  'gong': { slug: 'gong', color: '6366F1' },
  'hootsuite': { slug: 'hootsuite', color: '10B981' },
  'intercomfin': { slug: 'intercom', color: 'EF4444' },
  'jasper': { slug: 'jasper', color: '7C3AED' },
  'klaviyo': { slug: 'klaviyo', color: '3B82F6' },
  'marketmuse': { slug: 'marketmuse', color: 'F59E0B' },
  'phantombuster': { slug: 'phantom', color: '8B5CF6' },
  'surferseo': { slug: 'surfer', color: 'F97316' },
  'vidiq': { slug: 'vidiq', color: '06B6D4' },
  'arizeai': { slug: 'arize', color: 'F2A900' },
  'datadog': { slug: 'datadog', color: '632CA6' },
  'grafana': { slug: 'grafana', color: 'F46800' },
  'montecarlo': { slug: 'montecarlo', color: 'FF6B6B' },
  'newrelic': { slug: 'newrelic', color: '1CE783' },
  'aiva': { slug: 'aiva', color: '3B82F6' },
  'boomy': { slug: 'boomy', color: '22C55E' },
  'elevenlabs': { slug: 'eleven', color: '6366F1' },
  'lovo': { slug: 'lovo', color: 'F59E0B' },
  'mureka': { slug: 'mureka', color: 'E11D48' },
  'murf': { slug: 'murf', color: '06B6D4' },
  'soundraw': { slug: 'soundraw', color: '8B5CF6' },
  'logseq': { slug: 'logseq', color: '22C55E' },
  'mem': { slug: 'mem', color: '7C3AED' },
  'notion': { slug: 'notion', color: '000000' },
  'obsidian': { slug: 'obsidian', color: '483699' },
  'roamresearch': { slug: 'roamresearch', color: '3B82F6' },
  'tana': { slug: 'tana', color: '7C3AED' },
  'documize': { slug: 'documize', color: '3B82F6' },
  'firefliesai': { slug: 'fireflies', color: '8B5CF6' },
  'gamma': { slug: 'gamma', color: 'F97316' },
  'grammarly': { slug: 'grammarly', color: '7C3AED' },
  'motion': { slug: 'motion', color: 'EF4444' },
  'notionai': { slug: 'notion', color: 'EC4899' },
  'otterai': { slug: 'otter', color: '10B981' },
  'reclaimai': { slug: 'reclaim', color: '06B6D4' },
  'rowzero': { slug: 'row', color: 'F59E0B' },
  'superhuman': { slug: 'superhuman', color: '6366F1' },
  'anki': { slug: 'anki', color: 'EC4899' },
  'cheggai': { slug: 'chegg', color: 'EF4444' },
  'courseraai': { slug: 'coursera', color: 'F97316' },
  'elicit': { slug: 'elicit', color: '6366F1' },
  'guru': { slug: 'guru', color: '3B82F6' },
  'kimi': { slug: 'kimi', color: '10B981' },
  'scite': { slug: 'scite', color: 'F59E0B' },
  'apigee': { slug: 'googlecloud', color: 'F4B400' },
  'snyk': { slug: 'snyk', color: '4B32C3' },
  'sonarqube': { slug: 'sonarqube', color: '499CD2' },
  'checkmarx': { slug: 'checkmarx', color: '6366F1' },
  'crowdstrike': { slug: 'crowdstrike', color: 'EF4444' },
  'onfido': { slug: 'onfido', color: '3B82F6' },
  'sentinelone': { slug: 'sentinel', color: '10B981' },
  'veriff': { slug: 'veriff', color: 'F97316' },
  'buffer': { slug: 'buffer', color: '377E00' },
  'later': { slug: 'later', color: 'E85D75' },
  'socialpilot': { slug: 'socialpilot', color: 'FF4F00' },
  'googlesheetsai': { slug: 'googlesheets', color: '4285F4' },
  'quadratic': { slug: 'quadratic', color: '7C3AED' },
  'rows': { slug: 'rows', color: '217346' },
  'asana': { slug: 'asana', color: 'F06A6A' },
  'clickup': { slug: 'clickup', color: '7B68EE' },
  'mondaycom': { slug: 'monday', color: 'FF3D57' },
  'notionprojects': { slug: 'notion', color: 'E44D26' },
  'trello': { slug: 'trello', color: '2684FF' },
  'amazontranslate': { slug: 'amazon', color: 'FF9900' },
  'deepl': { slug: 'deepl', color: '0F2B46' },
  'googletranslate': { slug: 'googletranslate', color: '4285F4' },
  'laratranslate': { slug: 'lara', color: '10B981' },
  'microsofttranslator': { slug: 'microsofttranslator', color: '00A4EF' },
  'capcut': { slug: 'capcut', color: '00C7B7' },
  'did': { slug: 'did', color: 'F97316' },
  'heygen': { slug: 'hey', color: '22C55E' },
  'klingai': { slug: 'kling', color: 'FF6B00' },
  'lumadreammachine': { slug: 'luma', color: '8B5CF6' },
  'pikalabs': { slug: 'pika', color: 'EC4899' },
  'synthesia': { slug: 'synthesia', color: '3B82F6' },
  'veo': { slug: 'google', color: '4285F4' },
  'a0': { slug: 'a', color: '18181B' },
  'appgen': { slug: 'appgen', color: '10B981' },
  'blinknew': { slug: 'blink', color: 'A78BFA' },
  'boltdiy': { slug: 'bolt', color: 'F87171' },
  'boltnew': { slug: 'bolt', color: 'EF4444' },
  'dyad': { slug: 'dyad', color: '8B5CF6' },
  'firebasestudio': { slug: 'firebase', color: 'F59E0B' },
  'flutterflow': { slug: 'flutterflow', color: '2563EB' },
  'lovable': { slug: 'lovable', color: 'EC4899' },
  'meku': { slug: 'meku', color: 'EC4899' },
  'replit': { slug: 'replit', color: 'F97316' },
  'softr': { slug: 'softr', color: 'F59E0B' },
  'taskadegenesis': { slug: 'taskade', color: '06B6D4' },
  'weweb': { slug: 'weweb', color: '6366F1' },
  'anyword': { slug: 'anyword', color: 'EC4899' },
  'clearscope': { slug: 'clearscope', color: '6366F1' },
  'copyai': { slug: 'copyai', color: '6366F1' },
  'frase': { slug: 'frase', color: '06B6D4' },
  'ink': { slug: 'ink', color: 'F59E0B' },
  'quillbot': { slug: 'quillbot', color: '3B82F6' },
  'rytr': { slug: 'rytr', color: 'F59E0B' },
  'writer': { slug: 'writer', color: '7C3AED' },
  'writesonic': { slug: 'writesonic', color: '10B981' }
};

function getUpdatedIconUrl(toolName, toolUrl, iconLetter, color) {
  const nameLower = toolName.toLowerCase().replace(/[ .-]/g, '');
  const colorClean = color.replace('#', '');

  if (KNOWN_ICON_MAPPINGS[nameLower]) {
    const { slug } = KNOWN_ICON_MAPPINGS[nameLower];
    return `https://cdn.simpleicons.org/${slug}/${colorClean}`;
  }

  // Fallback to favicon
  const domain = toolUrl.replace(/^https?:\/\//, '').split('/')[0];
  return `https://www.google.com/s2/favicons?domain=${domain}&sz=128`;
}

function updateToolsJson(tools) {
  return tools.map(tool => ({
    ...tool,
    icon_url: getUpdatedIconUrl(tool.name, tool.url, tool.icon_letter, tool.color)
  }));
}

// Node.js usage
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { getUpdatedIconUrl, updateToolsJson, KNOWN_ICON_MAPPINGS };
}

// Browser usage
if (typeof window !== 'undefined') {
  window.ToolIconUpdater = { getUpdatedIconUrl, updateToolsJson, KNOWN_ICON_MAPPINGS };
}
