
import json

# Comprehensive icon mappings for AI tools
KNOWN_ICON_MAPPINGS = {
    'kaedim': ('threedotjs', '10B981'),
    'meshy': ('threedotjs', 'FF6B6B'),
    'spline': ('threejs', '6366F1'),
    'autify': ('testinglibrary', 'EC4899'),
    'bruno': ('bruno', '000000'),
    'functionize': ('jest', '6366F1'),
    'hoppscotch': ('hoppscotch', '10B981'),
    'jmeter': ('apachejmeter', 'D24939'),
    'postman': ('postman', 'FF6C37'),
    'qawolf': ('jest', '22C55E'),
    'soapui': ('soap', 'F4D03F'),
    'amplitude': ('amplitude', '00A4EF'),
    'googleanalytics': ('googleanalytics', 'E37400'),
    'mixpanel': ('mixpanel', '8B5CF6'),
    'askcodi': ('codecov', '00A4EF'),
    'chefbyconvex': ('chef', 'EF4444'),
    'coderabbit': ('githubactions', 'E11D48'),
    'devin': ('dev.to', 'F97316'),
    'githubcopilot': ('githubcopilot', '6366F1'),
    'googleduetai': ('google', '4285F4'),
    'googlestitch': ('google', '10B981'),
    'greptile': ('grep', 'F59E0B'),
    'jules': ('julia', '7C3AED'),
    'kiro': ('kibana', '06B6D4'),
    'manus': ('man', '3B82F6'),
    'memex': ('memcached', 'F59E0B'),
    'mindstudio': ('minds', '7C3AED'),
    'mocha': ('mocha', '92400E'),
    'pantoai': ('pantone', 'EF4444'),
    'pythagora': ('python', '8B5CF6'),
    'sourceryai': ('sourcetree', '3B82F6'),
    'workik': ('workplace', 'EC4899'),
    'activepieces': ('activecampaign', '635BFF'),
    'clockwise': ('clock', '3B82F6'),
    'fellow': ('fellowship', '7C3AED'),
    'make': ('make', '7B68EE'),
    'pabblyconnect': ('packagist', '00A4EF'),
    'powerautomate': ('microsoftpowerautomate', '0066FF'),
    'shortwave': ('shortwave', 'FF6B6B'),
    'n8n': ('n8n', 'FF6D5A'),
    'automationanywhere': ('robotframework', '10B981'),
    'axiom': ('axiom', 'EF4444'),
    'inflection': ('inflection', 'EC4899'),
    'lasso': ('lasso', '3B82F6'),
    'make.com': ('make', '6366F1'),
    'salesforceeinstein': ('salesforce', '8B5CF6'),
    'zapier': ('zapier', 'F97316'),
    'arc': ('arcbrowser', 'FC5C65'),
    'brave': ('brave', 'FB542B'),
    'diabrowser': ('dia', 'FF6B35'),
    'perplexitycomet': ('perplexity', '2088FF'),
    'sigmaaibrowser': ('sigma', '6366F1'),
    'freshdesk': ('freshdesk', 'FF6A00'),
    'hubspot': ('hubspot', 'FF7A59'),
    'intercom': ('intercom', '1F8DED'),
    'plain': ('plain', '1F8DED'),
    'salesforce': ('salesforce', '00A1E0'),
    'zendesk': ('zendesk', '03363D'),
    'zohocrm': ('zoho', 'E42527'),
    'characterai': ('characterai', 'EC4899'),
    'chatgpt': ('openai', '10A37F'),
    'copilot': ('microsoftcopilot', '6366F1'),
    'poe': ('poe', 'FF4500'),
    'replika': ('replika', '8B5CF6'),
    'youcom': ('you', 'FF6B35'),
    'adobefirefly': ('adobe', '6366F1'),
    'artafact': ('artifactregistry', 'F97316'),
    'canvaai': ('canva', 'F59E0B'),
    'dalle3': ('openai', '3B82F6'),
    'descript': ('descript', 'EC4899'),
    'illustrateai': ('illustrator', '14B8A6'),
    'lumaai': ('lumen', '3B82F6'),
    'midjourney': ('midjourney', 'EC4899'),
    'photoroom': ('photon', '22C55E'),
    'photon': ('photon', '8B5CF6'),
    'runway': ('runwayml', '8B5CF6'),
    'sora': ('openai', '06B6D4'),
    'stablediffusion': ('stabilityai', 'F97316'),
    'suno': ('sun', '10B981'),
    'udio': ('udacity', 'EF4444'),
    'alation': ('ala', 'F97316'),
    'anaplan': ('anaplan', '06B6D4'),
    'askai': ('ask', '8B5CF6'),
    'datarobot': ('datarobot', '3B82F6'),
    'looker': ('looker', '10B981'),
    'thoughtspot': ('thoughtspot', '6366F1'),
    'trifacta': ('trifacta', 'EF4444'),
    'voiceql': ('voice', 'EC4899'),
    'blazesql': ('blazemeter', 'EC4899'),
    'camelai': ('apachecamel', '10B981'),
    'consensus': ('consensus', '6366F1'),
    'juliusai': ('julia', 'F59E0B'),
    'scholarcy': ('scholar', 'F97316'),
    'semanticscholar': ('semanticweb', '7C3AED'),
    'firebase': ('firebase', 'FFCA28'),
    'neon': ('neon', '000000'),
    'railway': ('railway', '336791'),
    'supabase': ('supabase', '3ECF8E'),
    'turso': ('turso', '00E699'),
    'digitalocean': ('digitalocean', '0061FF'),
    'netlify': ('netlify', '00C7B7'),
    'render': ('render', '1B1F24'),
    'vercel': ('vercel', '000000'),
    'anima': ('anima', 'EF4444'),
    'beautifulai': ('beautifulsoup', 'FF6B6B'),
    'canva': ('canva', '00C4CC'),
    'codeparrot': ('codecov', '22C55E'),
    'codiaai': ('codio', 'F97316'),
    'emergent': ('emergency', '2563EB'),
    'figmamake': ('figma', 'A259FF'),
    'kromio': ('kroma', '7C3AED'),
    'leonardoai': ('leonardo', '22C55E'),
    'pitch': ('pitch', 'FF6B6B'),
    'rork': ('r', '06B6D4'),
    'tiledev': ('tile', '3B82F6'),
    'visme': ('visme', '6366F1'),
    'v0': ('v', '18181B'),
    'commitgen': ('commitlint', 'F59E0B'),
    'dataherald': ('datagrip', '8B5CF6'),
    'githubcopilotx': ('github', '6366F1'),
    'mabl': ('mabl', 'EF4444'),
    'repair': ('repair', '3B82F6'),
    'snykcode': ('snyk', 'F97316'),
    'sourcegraphcody': ('sourcegraph', '22C55E'),
    'stoplight': ('stoplight', '06B6D4'),
    'swimm': ('swim', 'EC4899'),
    'tabnine': ('tabnine', '10B981'),
    'chatpdf': ('chat', '3B82F6'),
    'humataai': ('humane', '10B981'),
    'knolli': ('knowledgebase', 'F59E0B'),
    'pdfai': ('pdf', '6366F1'),
    'updfai': ('up', 'EC4899'),
    'bigcommerce': ('bigcommerce', '000000'),
    'shopify': ('shopify', '96BF48'),
    'wixecommerce': ('wix', 'F7A600'),
    'antigravity': ('antigravity', '6366F1'),
    'atoms': ('atom', 'F97316'),
    'base44': ('base', '14B8A6'),
    'codegeex': ('codegeex', '10B981'),
    'continuedev': ('confluence', 'F59E0B'),
    'cursor': ('cursor', '7C3AED'),
    'fleet': ('fleet', '7C3AED'),
    'jetbrainsai': ('jetbrains', 'F97316'),
    'kilocode': ('kibana', 'EC4899'),
    'playcode': ('play', 'E11D48'),
    'qoder': ('qodana', '8B5CF6'),
    'trae': ('travis', '3B82F6'),
    'void': ('void', '18181B'),
    'windsurf': ('wind', '06B6D4'),
    'zed': ('zedindustries', '22C55E'),
    'bench': ('bench', 'F06B6B'),
    'wealthfront': ('wealthfront', '00D09C'),
    'jotform': ('jotform', 'FFA500'),
    'tally': ('tally', 'EF4444'),
    'typeform': ('typeform', '262627'),
    'greenhouse': ('greenhouse', 'FF6B6B'),
    'lever': ('lever', '4285F4'),
    'myfitnesspal': ('myfitnesspal', '22C55E'),
    'wysa': ('wysa', 'FF6B6B'),
    'ideogram': ('ide', '8B5CF6'),
    'imagen': ('google', '6366F1'),
    'nightcafe': ('night', 'F59E0B'),
    'artificialsolutions': ('artificialintelligence', '22C55E'),
    'ayasdi': ('ayasdi', 'EF4444'),
    'casetext': ('case', '10B981'),
    'deepmindalphafold': ('deepmind', '3B82F6'),
    'fourkite': ('four', '06B6D4'),
    'ironclad': ('iron', 'EC4899'),
    'paradox': ('paradox', 'F59E0B'),
    'pathai': ('path', '6366F1'),
    'zesty': ('zesty', '8B5CF6'),
    'zillowai': ('zillow', 'F97316'),
    'amazonq': ('aws', '3B82F6'),
    'claude': ('anthropic', 'FF6D00'),
    'claudehaiku': ('anthropic', '14B8A6'),
    'deepseek': ('deepseek', '06B6D4'),
    'gpt4': ('openai', '10B981'),
    'gpt4o': ('openai', 'A78BFA'),
    'gemini': ('google', '4285F4'),
    'grok': ('xai', 'EC4899'),
    'jurassic': ('jurassic', '8B5CF6'),
    'llama': ('meta', '6366F1'),
    'microsoftcopilot': ('microsoft', '22C55E'),
    'mistral': ('mistralai', 'F97316'),
    'perplexity': ('perplexity', 'EF4444'),
    'qwen': ('alibabacloud', 'F59E0B'),
    'stablelm': ('stabilityai', '84CC16'),
    'coursera': ('coursera', '0056D2'),
    'duolingo': ('duolingo', '58CC02'),
    'khanacademy': ('khanacademy', '00C7B7'),
    'udemy': ('udemy', 'A435F0'),
    'lexion': ('lexicon', '003366'),
    'adcreativeai': ('adcreative', 'EC4899'),
    'gong': ('gong', '6366F1'),
    'hootsuite': ('hootsuite', '10B981'),
    'intercomfin': ('intercom', 'EF4444'),
    'jasper': ('jasper', '7C3AED'),
    'klaviyo': ('klaviyo', '3B82F6'),
    'marketmuse': ('marketmuse', 'F59E0B'),
    'phantombuster': ('phantom', '8B5CF6'),
    'surferseo': ('surfer', 'F97316'),
    'vidiq': ('vidiq', '06B6D4'),
    'arizeai': ('arize', 'F2A900'),
    'datadog': ('datadog', '632CA6'),
    'grafana': ('grafana', 'F46800'),
    'montecarlo': ('montecarlo', 'FF6B6B'),
    'newrelic': ('newrelic', '1CE783'),
    'aiva': ('aiva', '3B82F6'),
    'boomy': ('boomy', '22C55E'),
    'elevenlabs': ('eleven', '6366F1'),
    'lovo': ('lovo', 'F59E0B'),
    'mureka': ('mureka', 'E11D48'),
    'murf': ('murf', '06B6D4'),
    'soundraw': ('soundraw', '8B5CF6'),
    'logseq': ('logseq', '22C55E'),
    'mem': ('mem', '7C3AED'),
    'notion': ('notion', '000000'),
    'obsidian': ('obsidian', '483699'),
    'roamresearch': ('roamresearch', '3B82F6'),
    'tana': ('tana', '7C3AED'),
    'documize': ('documize', '3B82F6'),
    'firefliesai': ('fireflies', '8B5CF6'),
    'gamma': ('gamma', 'F97316'),
    'grammarly': ('grammarly', '7C3AED'),
    'motion': ('motion', 'EF4444'),
    'notionai': ('notion', 'EC4899'),
    'otterai': ('otter', '10B981'),
    'reclaimai': ('reclaim', '06B6D4'),
    'rowzero': ('row', 'F59E0B'),
    'superhuman': ('superhuman', '6366F1'),
    'anki': ('anki', 'EC4899'),
    'cheggai': ('chegg', 'EF4444'),
    'courseraai': ('coursera', 'F97316'),
    'elicit': ('elicit', '6366F1'),
    'guru': ('guru', '3B82F6'),
    'kimi': ('kimi', '10B981'),
    'scite': ('scite', 'F59E0B'),
    'apigee': ('googlecloud', 'F4B400'),
    'snyk': ('snyk', '4B32C3'),
    'sonarqube': ('sonarqube', '499CD2'),
    'checkmarx': ('checkmarx', '6366F1'),
    'crowdstrike': ('crowdstrike', 'EF4444'),
    'onfido': ('onfido', '3B82F6'),
    'sentinelone': ('sentinel', '10B981'),
    'veriff': ('veriff', 'F97316'),
    'buffer': ('buffer', '377E00'),
    'later': ('later', 'E85D75'),
    'socialpilot': ('socialpilot', 'FF4F00'),
    'googlesheetsai': ('googlesheets', '4285F4'),
    'quadratic': ('quadratic', '7C3AED'),
    'rows': ('rows', '217346'),
    'asana': ('asana', 'F06A6A'),
    'clickup': ('clickup', '7B68EE'),
    'mondaycom': ('monday', 'FF3D57'),
    'notionprojects': ('notion', 'E44D26'),
    'trello': ('trello', '2684FF'),
    'amazontranslate': ('amazon', 'FF9900'),
    'deepl': ('deepl', '0F2B46'),
    'googletranslate': ('googletranslate', '4285F4'),
    'laratranslate': ('lara', '10B981'),
    'microsofttranslator': ('microsofttranslator', '00A4EF'),
    'capcut': ('capcut', '00C7B7'),
    'did': ('did', 'F97316'),
    'heygen': ('hey', '22C55E'),
    'klingai': ('kling', 'FF6B00'),
    'lumadreammachine': ('luma', '8B5CF6'),
    'pikalabs': ('pika', 'EC4899'),
    'synthesia': ('synthesia', '3B82F6'),
    'veo': ('google', '4285F4'),
    'a0': ('a', '18181B'),
    'appgen': ('appgen', '10B981'),
    'blinknew': ('blink', 'A78BFA'),
    'boltdiy': ('bolt', 'F87171'),
    'boltnew': ('bolt', 'EF4444'),
    'dyad': ('dyad', '8B5CF6'),
    'firebasestudio': ('firebase', 'F59E0B'),
    'flutterflow': ('flutterflow', '2563EB'),
    'lovable': ('lovable', 'EC4899'),
    'meku': ('meku', 'EC4899'),
    'replit': ('replit', 'F97316'),
    'softr': ('softr', 'F59E0B'),
    'taskadegenesis': ('taskade', '06B6D4'),
    'weweb': ('weweb', '6366F1'),
    'anyword': ('anyword', 'EC4899'),
    'clearscope': ('clearscope', '6366F1'),
    'copyai': ('copyai', '6366F1'),
    'frase': ('frase', '06B6D4'),
    'ink': ('ink', 'F59E0B'),
    'quillbot': ('quillbot', '3B82F6'),
    'rytr': ('rytr', 'F59E0B'),
    'writer': ('writer', '7C3AED'),
    'writesonic': ('writesonic', '10B981'),
}

def get_updated_icon_url(tool_name, tool_url, icon_letter, color):
    """Get the updated icon URL for a tool"""
    name_lower = tool_name.lower().replace(' ', '').replace('.', '').replace('-', '')
    color_clean = color.replace('#', '')

    if name_lower in KNOWN_ICON_MAPPINGS:
        slug, _ = KNOWN_ICON_MAPPINGS[name_lower]
        return f"https://cdn.simpleicons.org/{slug}/{color_clean}"

    # Fallback to favicon
    domain = tool_url.replace('https://', '').replace('http://', '').split('/')[0]
    return f"https://www.google.com/s2/favicons?domain={domain}&sz=128"

def update_tools_json(input_file, output_file):
    """Update all tool icons in the JSON file"""
    with open(input_file, 'r', encoding='utf-8') as f:
        tools = json.load(f)

    for tool in tools:
        tool['icon_url'] = get_updated_icon_url(
            tool['name'],
            tool['url'],
            tool['icon_letter'],
            tool['color']
        )

    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(tools, f, indent=2, ensure_ascii=False)

    print(f"✅ Updated {len(tools)} tools")
    print(f"💾 Output saved to: {output_file}")

if __name__ == "__main__":
    import sys
    if len(sys.argv) != 3:
        print("Usage: python update_tool_icons.py <input.json> <output.json>")
        sys.exit(1)

    update_tools_json(sys.argv[1], sys.argv[2])
