// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA86gH3SQKPTLFZHKgH_rJwJpKm9yhQ9vU',
    appId: '1:841500116943:web:9cfb5994f2f8b7e5e474ba',
    messagingSenderId: '841500116943',
    projectId: 'pookies-bunter-zone-ak-up',
    authDomain: 'pookies-bunter-zone-ak-up.firebaseapp.com',
    databaseURL: 'https://pookies-bunter-zone-ak-up-default-rtdb.firebaseio.com',
    storageBucket: 'pookies-bunter-zone-ak-up.firebasestorage.app',
    measurementId: 'G-GESWL04QL9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-dnx99fbaeiykriMlCIAMlGZaK90Gl7A',
    appId: '1:841500116943:ios:ffb7f988cd560c56e474ba',
    messagingSenderId: '841500116943',
    projectId: 'pookies-bunter-zone-ak-up',
    databaseURL: 'https://pookies-bunter-zone-ak-up-default-rtdb.firebaseio.com',
    storageBucket: 'pookies-bunter-zone-ak-up.firebasestorage.app',
    iosClientId: '841500116943-icdas1c4tftse2rsu5l6eecierg3bjl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.pookieBanterZoneMobile',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-dnx99fbaeiykriMlCIAMlGZaK90Gl7A',
    appId: '1:841500116943:ios:ffb7f988cd560c56e474ba',
    messagingSenderId: '841500116943',
    projectId: 'pookies-bunter-zone-ak-up',
    databaseURL: 'https://pookies-bunter-zone-ak-up-default-rtdb.firebaseio.com',
    storageBucket: 'pookies-bunter-zone-ak-up.firebasestorage.app',
    iosClientId: '841500116943-icdas1c4tftse2rsu5l6eecierg3bjl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.pookieBanterZoneMobile',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp6Yfs1-zRaGxwpF2KyidJ6d9wtRLkSlE',
    appId: '1:841500116943:android:d1f1acae8ae3cb74e474ba',
    messagingSenderId: '841500116943',
    projectId: 'pookies-bunter-zone-ak-up',
    databaseURL: 'https://pookies-bunter-zone-ak-up-default-rtdb.firebaseio.com',
    storageBucket: 'pookies-bunter-zone-ak-up.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC2W3yFbJ7v81kSAHmDkW-pK1ndK91Jpc',
    appId: '1:841500116943:web:cab30fe5295b7907e474ba',
    messagingSenderId: '841500116943',
    projectId: 'pookies-bunter-zone-ak-up',
    authDomain: 'pookies-bunter-zone-ak-up.firebaseapp.com',
    databaseURL: 'https://pookies-bunter-zone-ak-up-default-rtdb.firebaseio.com',
    storageBucket: 'pookies-bunter-zone-ak-up.firebasestorage.app',
    measurementId: 'G-W7JWTZJGTR',
  );

}